name: API Testing Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

env:
  NODE_VERSION: '16'
  NEWMAN_VERSION: '5.3.2'
  REPORTER_VERSION: '1.0.5'

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create Results Directory
        run: |
          mkdir -p test-results/poetry
          mkdir -p test-results/catfacts

      - name: Run PoetryDB API Tests
        continue-on-error: true  # Continue to next step even if this fails
        run: |
          newman run collections/PoetryDB_API_Tests.postman_collection.json \
          -e environments/dev.json \
          -r cli,htmlextra,junitfull \
          --reporter-htmlextra-export test-results/poetry/report.html \
          --reporter-junitfull-export test-results/poetry/junit-report.xml

      - name: Run Cat Facts API Tests
        continue-on-error: true
        run: |
          newman run collections/Cat_Facts_API_Tests.postman_collection.json \
          -e environments/dev.json \
          -r cli,htmlextra,junitfull \
          --reporter-htmlextra-export test-results/catfacts/report.html \
          --reporter-junitfull-export test-results/catfacts/junit-report.xml

      - name: Check Test Results
        id: check-results
        run: |
          if [ -f test-results/poetry/junit-report.xml ] && [ -f test-results/catfacts/junit-report.xml ]; then
            echo "All test reports generated successfully"
            exit 0
          else
            echo "Some test reports are missing"
            exit 1
          fi

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Test Results
          path: "test-results/**/junit-report.xml"
          reporter: java-junit
          fail-on-error: false

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-results/
          retention-days: 30